name: Release

on:
  push:
    branches:
      - main
      - beta

jobs:
  release:
    name: Release process
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GHP }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          SEMANTIC_RELEASE_NPM_PUBLISH: 'true'
          SEMANTIC_RELEASE_SLACK_WEBHOOK: ${{ secrets.SEMANTIC_RELEASE_SLACK_WEBHOOK }}
        run: npx semantic-release

      - name: Rebase dev branch (keep linear history)
        run: |
          git fetch --no-tags origin 1-dev:1-dev
          git rebase ${GITHUB_REF_NAME} 1-dev
          git push origin 1-dev
